### ISSUE TITLE
Compilation failed (Linux)

### ISSUE THREAD

**Issue by anemol** [OBAViJEST/boatcoinfinal#1]
Linux 64 bits:

make -f makefile.unix

`obj/miner.o : Dans la fonction « ~CTxDB » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/main.o : Dans la fonction « ~CTxDB » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/main.o:/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : encore plus de références indéfinies suivent vers « leveldb::WriteBatch::~WriteBatch() »
obj/smessage.o : Dans la fonction « SecMsgDB::Open(char const*) » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:219 : référence indéfinie vers « leveldb::Options::Options() »
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:221 : référence indéfinie vers « leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**) »
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:225 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/smessage.o : Dans la fonction « SecMsgDB::ScanBatch(CDataStream const&, std::string*, bool*) const » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:280 : référence indéfinie vers « leveldb::WriteBatch::Iterate(leveldb::WriteBatch::Handler*) const »
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:283 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/smessage.o : Dans la fonction « ~SecMsgBatchScanner » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:235 : référence indéfinie vers « leveldb::WriteBatch::Handler::~Handler() »
obj/smessage.o : Dans la fonction « SecMsgDB::TxnBegin() » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:294 : référence indéfinie vers « leveldb::WriteBatch::WriteBatch() »
obj/smessage.o : Dans la fonction « SecMsgDB::TxnCommit() » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:306 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:311 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/smessage.o : Dans la fonction « SecMsgDB::TxnAbort() » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:320 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/smessage.o : Dans la fonction « SecMsgDB::EraseSmesg(unsigned char*) » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:576 : référence indéfinie vers « leveldb::WriteBatch::Delete(leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:586 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/smessage.o : Dans la fonction « SecMsgDB::WritePK(CKeyID&, CPubKey&) » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:386 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:395 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/smessage.o : Dans la fonction « SecMsgDB::WriteSmesg(unsigned char*, SecMsgStored&) » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:530 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:539 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/smessage.o : Dans la fonction « SecMsgDB::ReadPK(CKeyID&, CPubKey&) » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:354 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/smessage.o : Dans la fonction « ~SecMsgDB » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.h:295 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
/media/SSD/Workspace/boatcoinfinal/src/smessage.h:295 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
/media/SSD/Workspace/boatcoinfinal/src/smessage.h:295 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/smessage.o : Dans la fonction « SecureMsgScanBlock(CBlock&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/smessage.o : Dans la fonction « ~SecMsgDB » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.h:295 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/smessage.o:/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : encore plus de références indéfinies suivent vers « leveldb::WriteBatch::~WriteBatch() »
obj/smessage.o : Dans la fonction « SecMsgDB::ReadSmesg(unsigned char*, SecMsgStored&) » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:502 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/smessage.o : Dans la fonction « ThreadSecureMsgPow(void*) » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.h:295 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/smessage.o : Dans la fonction « SecMsgBatchScanner::~SecMsgBatchScanner() » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:235 : référence indéfinie vers « leveldb::WriteBatch::Handler::~Handler() »
obj/smessage.o : Dans la fonction « ~SecMsgBatchScanner » :
/media/SSD/Workspace/boatcoinfinal/src/smessage.cpp:235 : référence indéfinie vers « leveldb::WriteBatch::Handler::~Handler() »
obj/smessage.o:(.rodata._ZTI18SecMsgBatchScanner[_ZTI18SecMsgBatchScanner]+0x10) : référence indéfinie vers « typeinfo for leveldb::WriteBatch::Handler »
obj/txdb-leveldb.o : Dans la fonction « init_blockindex(leveldb::Options&, bool) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:46 : référence indéfinie vers « leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:48 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « CTxDB::Close() » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:117 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/txdb-leveldb.o : Dans la fonction « CTxDB::TxnBegin() » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:124 : référence indéfinie vers « leveldb::WriteBatch::WriteBatch() »
obj/txdb-leveldb.o : Dans la fonction « CTxDB::TxnCommit() » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:132 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:135 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « CTxDB::ScanBatch(CDataStream const&, std::string*, bool*) const » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:178 : référence indéfinie vers « leveldb::WriteBatch::Iterate(leveldb::WriteBatch::Handler*) const »
obj/txdb-leveldb.o : Dans la fonction « ~CBatchScanner » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:141 : référence indéfinie vers « leveldb::WriteBatch::Handler::~Handler() »
obj/txdb-leveldb.o : Dans la fonction « CTxDB::ScanBatch(CDataStream const&, std::string*, bool*) const » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:180 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « CTxDB::CTxDB(char const*) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:54 : référence indéfinie vers « leveldb::Options::Options() »
obj/txdb-leveldb.o : Dans la fonction « GetOptions » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:29 : référence indéfinie vers « leveldb::Options::Options() »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:31 : référence indéfinie vers « leveldb::NewLRUCache(unsigned long) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:32 : référence indéfinie vers « leveldb::NewBloomFilterPolicy(int) »
obj/txdb-leveldb.o : Dans la fonction « CTxDB::CTxDB(char const*) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:69 : référence indéfinie vers « leveldb::NewBloomFilterPolicy(int) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:86 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/txdb-leveldb.o : Dans la fonction « Erase<std::pair<std::basic_string<char>, uint256> > » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:137 : référence indéfinie vers « leveldb::WriteBatch::Delete(leveldb::Slice const&) »
obj/txdb-leveldb.o : Dans la fonction « ~CTxDB » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:37 : référence indéfinie vers « leveldb::WriteBatch::~WriteBatch() »
obj/txdb-leveldb.o : Dans la fonction « CBatchScanner::~CBatchScanner() » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:141 : référence indéfinie vers « leveldb::WriteBatch::Handler::~Handler() »
obj/txdb-leveldb.o : Dans la fonction « ~CBatchScanner » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.cpp:141 : référence indéfinie vers « leveldb::WriteBatch::Handler::~Handler() »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Read<std::string, int>(std::string const&, int&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:84 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Read<std::string, uint256>(std::string const&, uint256&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:84 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Read<std::string, std::string>(std::string const&, std::string&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:84 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Write<std::string, std::string>(std::string const&, std::string const&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:114 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:119 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Write<std::string, int>(std::string const&, int const&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:114 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:119 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Write<std::pair<std::string, uint256>, CDiskBlockIndex>(std::pair<std::string, uint256> const&, CDiskBlockIndex const&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:114 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:119 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Read<std::pair<std::string, uint256>, CTxIndex>(std::pair<std::string, uint256> const&, CTxIndex&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:84 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Write<std::string, uint256>(std::string const&, uint256 const&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:114 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:119 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Read<std::string, CBigNum>(std::string const&, CBigNum&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:84 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Write<std::string, CBigNum>(std::string const&, CBigNum const&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:114 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:119 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o : Dans la fonction « bool CTxDB::Write<std::pair<std::string, uint256>, CTxIndex>(std::pair<std::string, uint256> const&, CTxIndex const&) » :
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:114 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:119 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o:(.rodata._ZTI13CBatchScanner[_ZTI13CBatchScanner]+0x10) : référence indéfinie vers « typeinfo for leveldb::WriteBatch::Handler »
collect2: error: ld returned 1 exit status
make: *** [doubloond] Erreur 1
`

**Comment by OBAViJEST** [comment]
cd ~
git clone https://github.com/OBAViJEST/boatcoinfinal
cd ~/boatcoinfinal/src
chmod a+x leveldb/build_detect_platform
make -f makefile.unix USE_UPNP=-

**Comment by anemol** [comment]
Same thing. I already changed build_detect_platform with a chmod 755 leveldb/build_detect_platform. (a reccurent error for altcoins)

```
...
media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:114 : référence indéfinie vers « leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&) »
/media/SSD/Workspace/boatcoinfinal/src/txdb-leveldb.h:119 : référence indéfinie vers « leveldb::Status::ToString() const »
obj/txdb-leveldb.o:(.rodata._ZTI13CBatchScanner[_ZTI13CBatchScanner]+0x10) : référence indéfinie vers « typeinfo for leveldb::WriteBatch::Handler »
collect2: error: ld returned 1 exit status
make: *** [doubloond] Erreur 1

```

**Comment by OBAViJEST** [comment]
cd ~/boatcoinfinal/src/leveldb 
make clean

then 

cd ~/boatcoinfinal/src
make clean -f makefile.unix 
make -f makefile.unix USE_UPNP=-

**Comment by anemol** [comment]
It's ok now. Thanks.
